 /*************************************************************************
 * This file was generated by CRUST by an automated semantics preserving
 * translation from C/C++ to Rust
 * CRUST isn't perfect and may require manual editing
 * Check warnings and errors and refer to the official Rust Documentation
 ************************************************************************/
 /* Inline Functions for keyword-list.{h,cc}.

   Copyright (C) 2002-2003 Free Software Foundation, Inc.
   Written by Bruno Haible <bruno@clisp.org>.

   
 
 
 /* -------------------------- Keyword_List class --------------------------- */
 
 
 /* Access to first element of list.  */
 
 
/** Declaration of a structure should be completed with initialization of it's fields
 * It should be in the following format
 * let variable:struct_name = struct_name { member1:value1, member2:value2,..}
 */ let Keyword = INLINE { }; 
 
 
 /* Access to next element of list.  */
 
 
/** Declaration of a structure should be completed with initialization of it's fields
 * It should be in the following format
 * let variable:struct_name = struct_name { member1:value1, member2:value2,..}
 */ let Keyword_List = INLINE { }; 
 
 
 /* ------------------------- KeywordExt_List class ------------------------- */
 
 
 /* Access to first element of list.  */
 
 
/** Declaration of a structure should be completed with initialization of it's fields
 * It should be in the following format
 * let variable:struct_name = struct_name { member1:value1, member2:value2,..}
 */ let KeywordExt = INLINE { }; 
 
 
 /* Access to next element of list.  */
 
 
/** Declaration of a structure should be completed with initialization of it's fields
 * It should be in the following format
 * let variable:struct_name = struct_name { member1:value1, member2:value2,..}
 */ let KeywordExt_List = INLINE { }; 
 
